bootstrap script updated for PLD

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -16,6 +16,19 @@ if command -v lsb_release >/dev/null 2>&1; then
 			exit 1
 	    fi
 	    ;;
+	PLD)
+	    for package in python-virtualenv; do
+		if ! rpm -q $package >/dev/null 2>&1; then
+                    # add a space after old values
+		    missing="${missing:+$missing }$package"
+		fi
+	    done
+	    if [ -n "$missing" ]; then
+			echo "$0: missing required packages, please install them:" 1>&2
+			echo "  poldek --cmd install $missing"
+			exit 1
+	    fi
+	    ;;
     esac
 
     case "$(lsb_release --id --short | awk '{print $1}')" in
